### ISSUE TITLE
Can we ignore case sensitivity when starting completion?

### ISSUE THREAD

**Issue by yonta** [lincheney/fzf-tab-completion#109]
Is it possible to display completion candidates while ignoring the case of already entered characters at the start of completion?
I would like to achieve behavior similar to setting set completion-ignore-case on in bash.

### real behavior

```console
$ ls
hoge1 hoge2 HOGE3
$ ls h<TAB>
> ls h
  2/2 -----
  hoge2/
  hoge1/
```

### want behavior

```console
$ ls
hoge1 hoge2 HOGE3
$ ls h<TAB>
> ls h
  2/2 -----
  HOGE3/
  hoge2/
  hoge1/
```

**Comment by yonta** [comment]
Sorry, this probrem is by not fzf-tab-completion, but original fzf.

**Comment by d-enk** [comment]
@yonta you just can add 
`FZF_COMPLETION_OPTS="$FZF_COMPLETION_OPTS --ignore-case"`
for bash
`bind 'set completion-ignore-case on'`

**Comment by yonta** [comment]
The issue seems to stem from a conflict between `fzf` and `inputrc`.
For the benefit of others, I'll leave a note on how to resolve this.

## Working Code

```bash
# Add this to .bashrc or similar
bind -s "set completion-ignore-case on"
```

## Non-Working Code

```bash
# Added to inputrc
set bell-style none
```

**Comment by yonta** [comment]
@d-enk thanks!

I was able to resolve the issue with `bind 'set completion-ignore-case on'`.
