### ISSUE TITLE
Avoid opening fzf before getting the completion list

### ISSUE THREAD

**Issue by przepompownia** [lincheney/fzf-tab-completion#110]
fzf turns out to be used also when there is only one result. Here is bash example that show it (better visible when `FZF_DEFAULT_OPTS` contains `--tmux`)

```bash
_foo() { sleep 1; COMPREPLY=(foo1); }
complete -F _foo foo
```

Is it difficult to process the result before sending it to fzf?

Maybe #29 is related.

**Comment by przepompownia** [comment]
> `fzf --sync` ?

It did not not prevent from opening the popup window (when added to `FZF_DEFAULT_OPTS`).

**Comment by d-enk** [comment]
try

`{ echo 1; sleep 1; echo 2; } | fzf --sync`

**Comment by przepompownia** [comment]
Thanks for the example. For better reproduction
```sh
{ echo 1; sleep 1; echo 2; } | FZF_DEFAULT_OPTS='--sync' fzf
```

@d-enk on the recent tmux try 
```sh
{ echo 1; sleep 1; echo 2; } | FZF_DEFAULT_OPTS='--tmux --sync' fzf
```
I see the difference (both with and without `--tmux`), although the empty popup window still appears before the result is available. 

If the input result is provided as a herestring 
```sh
FZF_DEFAULT_OPTS=--tmux fzf <<<$(sleep 1; echo 1; sleep 1; echo 2)
```
fzf waits for the whole result (so behaves like `--sync` if I'm not wrong) before calling `display-popup`.

**Comment by przepompownia** [comment]
Our examples make me realize that 
- the cost of this feature is synchronicity - not always wanted so it could be optional,
- passing the result through herestring instead of pipe can be helpful if the user allowed that cost.

**Comment by d-enk** [comment]
I don't have any empty popup window with/without `--tmux`

```bash
FZF_DEFAULT_OPTS=--tmux fzf <<<$(sleep 1; echo 1; sleep 1; echo 2)
```

here fzf just waits when string was builded

**Comment by lincheney** [comment]
I can reproduce by doing `FZF_DEFAULT_OPTS='--tmux' fzf < <(sleep 1; echo 1)`

There's something similar for zsh already and I've copied some over to the bash completion as well https://github.com/lincheney/fzf-tab-completion/commit/7979a16dee5970b9f0091609b07174c9ac887472
which should help, so it will not start fzf unless there are at least 2 matches.

**Comment by przepompownia** [comment]
Confirmed: for single element reply I get no redundant fzf popup. Thank you!

>  I've copied some over to the bash completion as well [7979a16](https://github.com/lincheney/fzf-tab-completion/commit/7979a16dee5970b9f0091609b07174c9ac887472) which should help, so it will not start fzf unless there are at least 2 matches.

**Comment by przepompownia** [comment]
Unfortunately some regression came with this change:
![image](https://github.com/user-attachments/assets/ff5aa688-a408-4895-9a79-856519c2b9ee)
![image](https://github.com/user-attachments/assets/6877bd3b-3a8e-45ad-ad60-be14377ffb6a)

I need some free time to create a repro.

**Comment by lincheney** [comment]
ahh i must have messed up one of the nth flags, let me check

**Comment by lincheney** [comment]
can you try with this https://github.com/lincheney/fzf-tab-completion/commit/3e9ff06ad195d4b36dd9d59caa62f39fc7cd354c

**Comment by d-enk** [comment]
@lincheney, please explain me why the fzf option `--select-1` `(-1)` was not enough?

**Comment by przepompownia** [comment]
> can you try with this [3e9ff06](https://github.com/lincheney/fzf-tab-completion/commit/3e9ff06ad195d4b36dd9d59caa62f39fc7cd354c)

Works correctly, thank you!

**Comment by lincheney** [comment]
> @lincheney, please explain me why the fzf option `--select-1` `(-1)` was not enough?

I assume it is some fzf behaviour. 
When I run `sleep 3 | fzf --tmux -0 -1` or `(sleep 3; echo 123) | fzf --tmux -0 -1` in tmux it still opens the popup
