### ISSUE TITLE
[Request/Help] Change color of the search string

### ISSUE THREAD

**Issue by egirlcatnip** [lincheney/fzf-tab-completion#111]
How can I change the gray color that is shown when the term i'm auto-completing is filled from the shell prompt?

Example:
![image](https://github.com/user-attachments/assets/18e2dded-9023-4b0f-898e-169c1df1ba31)

ech part of the > echo

note: I did not manually type out "ech", it got inputted as I opened the completetion.

**Comment by d-enk** [comment]
```bash
FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS --color=prompt:#FF0000"
```

**Comment by egirlcatnip** [comment]
I'm afraid this doesn't fix it..
![image](https://github.com/user-attachments/assets/5b1f0564-b6f1-493d-9085-50d81708516a)

**Comment by d-enk** [comment]
`--color='fg:#FF0000,fg+:#00FF00'`

**Comment by egirlcatnip** [comment]
nope..
![image](https://github.com/user-attachments/assets/30d9b4ae-3654-4520-8e44-e0bbd216d7de)

**Comment by d-enk** [comment]
https://github.com/lincheney/fzf-tab-completion/blob/11122590127ab62c51dd4bbfd0d432cee30f9984/bash/fzf-bash-completion.sh#L382

need replace/remove
`"\x1b[37m"` `"\x1b[0m"`

**Comment by egirlcatnip** [comment]
I'm using zsh, sorry I'm getting confused..

**Comment by d-enk** [comment]
same

https://github.com/lincheney/fzf-tab-completion/blob/11122590127ab62c51dd4bbfd0d432cee30f9984/zsh/fzf-zsh-completion.sh#L343-L349

**Comment by egirlcatnip** [comment]
I was able to configure it how I like it with this, thank you <3

**Comment by lincheney** [comment]
For zsh only, this is now configurable using a zstyle
https://github.com/lincheney/fzf-tab-completion/commit/5bbbf619646c6ec307fee863c91e98825fc7d2e9
