### ISSUE TITLE
Having a lot of strange underscore things when using command completion

### ISSUE THREAD

**Issue by alexshelkov** [lincheney/fzf-tab-completion#12]
For example if I type `ifconfig`[TAB] I will see this:

![image](https://user-images.githubusercontent.com/1233347/82962172-473f2500-9fe1-11ea-8e08-5effb8591e1d.png)

And all other commands have same underscore equivalents.

**Comment by lincheney** [comment]
I assume you are using `zsh`.
Do you have approximate completion turned on? That might be causing those ones to turn up.
ie something like this in your `~/.zshrc`
```
zstyle ':completion:*' completer _complete _approximate
zstyle ':completion:*' max-errors 1
```
The underscore ones in zsh are valid, but I agree not usually what you want.

**Comment by alexshelkov** [comment]
Thx for response, but I have to move to other solution, so I can't re-try it now.
