### ISSUE TITLE
Do fuzzy completion

### ISSUE THREAD

**Issue by nkh** [lincheney/fzf-tab-completion#13]
if a program has option --display_some_data it is not possible to find the option with 'dissd', 'dis' does find the option and all other options starting with 'dis' but the bus stops there.

**Comment by lincheney** [comment]
That sounds like you have exact match enabled in fzf (the `-e` or `--exact` flag).
Can you check your fzf options, in particular `$FZF_DEFAULT_OPTS` and `$FZF_COMPLETION_OPTS`.

**Comment by nkh** [comment]
Both are empty, and I use fzf all day long, this is the only place where fuzzy search is not working.

**Comment by nkh** [comment]
oops! well it seems that I se it all day long via other commands than my own aliased fzf which indeed does have a -e in it.

Checked the environment variables but not the alias. Thanks.
