### ISSUE TITLE
[Documentation] The docs say to install readline- Is that necessary, or does cargo take care of it for us?

### ISSUE THREAD

**Issue by matthewstrasiotto** [lincheney/fzf-tab-completion#14]
The relevant lines:

https://github.com/lincheney/fzf-tab-completion/blob/4d59a4409115a3524400ed77fb1df594f5205eef/README.md#L98-L106

It's not clear to me how to install the rl_custom_function, besides just building it. 

It also appears that a shared object is built when I build the crate in "readline", (under target) Is that just the project-local dependency `rl_custom_function` (from the rl_custom_function package), or does that object depend on rl_custom_function, and that is the compiled fzf-tab-completion source?

Thanks!

**Comment by lincheney** [comment]
Yes, all you have to do is build it, and then reference the path to the .so later in `LD_PRELOAD`.
I'll reword the readme to make it a bit clearer.

**Comment by mstr3336** [comment]
Thanks!
