### ISSUE TITLE
completion removes > symbol

### ISSUE THREAD

**Issue by laur89** [lincheney/fzf-tab-completion#17]
**Reproduce:**
`echo a >/dev<TAB>`

gets completed into
`echo a /dev/`

OS: debian testing
shell: bash version 5.0.18(1)-release
fzf-tab-completion: `527ac6c`
fzf: `0.23.1 (fc7630a)`
Only using the bash hook (ie without readline modification)

**Comment by lincheney** [comment]
hi, this has been fixed in #20
