### ISSUE TITLE
Bash - Completion problems with aliases

### ISSUE THREAD

**Issue by tseeker** [lincheney/fzf-tab-completion#24]
**Description**

Various (but most likely related) issues occur when trying to use completion right after an alias (before adding a space).

- If the alias is a single word, possible completions for that word will be displayed instead of completions for commands stating with the alias.
```
alias x='git'
x<TAB>
# List of all commands starting with the word "git" appear.
# Expected: list of commands that start with "x"
```

- If the alias ends with a part for which completion is supported, completion for that element will display possible replacements for the last part of the alias.
```
alias gp='git pull'
gp<TAB>
# List of all git command is displayed
# Expected: list of commands that start with "gp"
```

- In all cases, selecting anything from the list will cause an error :
```
-bash: -${#cur}: substring expression < 0
```

**Environment**

- Devuan Testing
- OS-provided Bash 5.0.3 / fzf 0.17.5
- fzf-tab-completion 527ac6c

**Comment by lincheney** [comment]
closed by #27
