### ISSUE TITLE
Bash completion actually requires GNU Awk

### ISSUE THREAD

**Issue by tseeker** [lincheney/fzf-tab-completion#28]
**Description**

Trying to use the bash completion code with `mawk` installed (instead of `gawk`) doesn't work. The completions are listed but it is impossible to select them.

The problem is caused by the fact that `fzf-bash-completion.sh` line 254 doesn't do what it should when `mawk` is in use, leaving the input untouched.

**Environment**

- Devuan Testing
- OS-provided Bash 5.0.3 / fzf 0.24
- mawk 1.3.3
- fzf-tab-completion b2f6bdb18f6d81330b7fdee02c67903d5f44e48e

**Comment by zcaudate** [comment]
I replaced  `sed` to `gsed` and `awk` to `gawk` in order to get it working

https://github.com/lincheney/fzf-tab-completion/compare/master...zcaudate:master

I'm not great with bash script can these commands be parameterized depending on the os?

**Comment by lincheney** [comment]
looks like mawk does not support `.{n}` style regexes, I've converted it to use `substr()` which is probably better anyway
https://github.com/lincheney/fzf-tab-completion/commit/516c4c1925e504edb3519b699f15eb6acd5c9054
Can you try with this and see if it resolves your issue?
