### ISSUE TITLE
How to use abbrev path completion in Bash?

### ISSUE THREAD

**Issue by edentsai** [lincheney/fzf-tab-completion#30]
I saw it can use `ls /u/s/zsh<Tab>` to complete `ls /usr/sbin/zsh` in [example.svg](https://github.com/lincheney/fzf-tab-completion/blob/master/example.svg),
but I can't finger out how to use the feature about abbrev path completion.

I tried `ls /u/l/b/bash<Tab>` to complete the abbrev path to `ls /usr/local/bin/bash` for me in Bash on macOS, but it doesn't works.

for example:

```sh
$ which bash
/usr/local/bin/bash
```
```sh
# It doesn't works if I use fzf-tab-completion with `<Tab>` without **
$ ls /u/l/b/bash<Tab>
# no any completion result.

# when path is only one directory.
$ ls /u<Tab>
> ls /u < 2/2 (0)
> /Users/
> /Usr/
```

```sh
# It works if I only use fzf built-in feature with abbrev path, 
# without fzf-tab-completion
$ ls /u/l/b/bash**<Tab>
> u/l/b/bash  < 29302/88790 (0)
> /usr/local/bin/bash
> ...
```

my workstation environment:

- macOS Big Sur
- Bash 5.1.4 (installed by Homebrew)
- fzf 0.25.1 (installed by Homebrew)
- install fzf-tab-completion with the following commands:

  ```sh
  source /path/to/fzf-tab-completion/bash/fzf-bash-completion.sh
  bind -x '"\t": fzf_bash_completion'
  ```

Did I missed something in [README.md](https://github.com/lincheney/fzf-tab-completion#bash)?   
or should I install the readline `rl_custom_complete` library?

thanks.

**Comment by lincheney** [comment]
That's only available in zsh feature, its not available in bash.
(To be specific, it's a feature of the zsh shell itself, not something implemented in the fzf-tab-completion scripts.)
