### ISSUE TITLE
_fzf_completion_preexit:which:2: bad option: -f

### ISSUE THREAD

**Issue by tshu-w** [lincheney/fzf-tab-completion#31]
I got the following error when enabling `fzf-tab-completion`, though it seems that partially working.
```
_fzf_completion_preexit:which:2: bad option: -f
_fzf_completion_preexit:which:2: bad option: -f
_fzf_completion_preexit:which:2: bad option: -z
```

macOS 11.2
zsh 5.8 (x86_64-apple-darwin20.0)

**Comment by lincheney** [comment]
I've pushed https://github.com/lincheney/fzf-tab-completion/commit/6c16a61601f8cf0f751b61008bb853cfc618c69c which I believe should fix it.
Can you try that and see if you still get those messages?

**Comment by tshu-w** [comment]
@lincheney Thx for you effort, those messages don't appear any more. However, the appearance of fzf and the confirmation of candidates is a bit slow, I don't know where the problem is
