### ISSUE TITLE
pygmentize: error: unrecognized arguments: s

### ISSUE THREAD

**Issue by asaf-erlich** [lincheney/fzf-tab-completion#39]
I'm using fzf-tab-completion on a mac which also has oh-my-zsh and a few plugins that interact poorly to create the below error. I believe fzf's default colorization is being sent to pygmentize, a python library. And that is complaining that some flag that fzf-tab-completion is not valid only in some circumstances. Most of the time tab completion is fine, but in rare cases (and I'm not 100% sure on the root cause) I see the below error output instead of the fzf preview I expect.

```
usage: pygmentize [-l LEXER | -g] [-F FILTER[:options]] [-f FORMATTER]
                  [-O OPTION=value[,OPTION=value,...]] [-P OPTION=value]
                  [-o OUTPUTFILE] [-v] [-s] [-x]
                  [-S STYLE -f formatter | -L [WHAT ...] | -N FILENAME | -C |
                  -H NAME TYPE | -V | -h] [-a ARG]
                  [INPUTFILE]
pygmentize: error: unrecognized arguments: s
usage: pygmentize [-l LEXER | -g] [-F FILTER[:options]] [-f FORMATTER]
                  [-O OPTION=value[,OPTION=value,...]] [-P OPTION=value]
                  [-o OUTPUTFILE] [-v] [-s] [-x]
                  [-S STYLE -f formatter | -L [WHAT ...] | -N FILENAME | -C |
                  -H NAME TYPE | -V | -h] [-a ARG]
                  [INPUTFILE]
pygmentize: error: unrecognized arguments: s
usage: pygmentize [-l LEXER | -g] [-F FILTER[:options]] [-f FORMATTER]
                  [-O OPTION=value[,OPTION=value,...]] [-P OPTION=value]
                  [-o OUTPUTFILE] [-v] [-s] [-x]
                  [-S STYLE -f formatter | -L [WHAT ...] | -N FILENAME | -C |
                  -H NAME TYPE | -V | -h] [-a ARG]
                  [INPUTFILE]
pygmentize: error: unrecognized arguments: s
```

I'm not 100% sure what the root cause is here. It may not actually be fzf-tab-completion, but a combination of other oh-my-zsh plugins (such as https://github.com/zsh-users/zsh-completions ) that are leading to this error. Unfortunately I'm not good enough with how zsh completion works to know how to properly debug this error. My gut tells me this is a version compatibility issue with different completion tools + fzf + preview tooling. But it only happens when fzf tab completion is enabled.

If you have any suggestions on how to debug the root cause here to help figure out where the issue comes from I would appreciate it. When fzf tab completion works correctly I really like it so would prefer to go back to using it if possible. 

Thank you,
-Asaf

**Comment by stnma7e** [comment]
I am also experiencing this. Did you find a workaround?

**Comment by asaf-erlich** [comment]
@stnma7e unfortunately I just stopped using fzf-tab-completion so I never root caused this error.

**Comment by cerebrate** [comment]
I have this same error in Debian under WSL, using fzf-tab-completion.

**Comment by lincheney** [comment]
@cerebrate thanks for tracking that down for me
I've made a change to stop it from expanding aliases in the code (but I believe alias tab completion should still work): https://github.com/lincheney/fzf-tab-completion/commit/3dfaca917cd862f6f1299f1be47a30d19303258b
If you are able to try this out for me?

**Comment by cerebrate** [comment]
That seems to cure the problem for me, and I am still able to tab-complete aliases, so I think it's all good. Thanks!
