### ISSUE TITLE
PROMPT disapperaed after completion in Alacritty

### ISSUE THREAD

**Issue by Aloxaf** [lincheney/fzf-tab-completion#4]
Amazing work! It works perfectly and is even better than fzf-tab.

But there is a little problem:
![Peek 2019-12-31 12-39](https://user-images.githubusercontent.com/17017672/71610293-b9464600-2bca-11ea-968b-7876d9fc20ab.gif)

Here is the theme I'm using: https://github.com/Aloxaf/pure

**Comment by lincheney** [comment]
hmmm, unfortunately I'm not able to reproduce the issue. The prompt is still showing up for me even using your theme.
Do you have a minimal `.zshrc` that shows the problem?

This is what I've tried
```
autoload -Uz compinit
compinit

source ~/.zsh.d/fzf-zsh-completion.zsh
bindkey '^I' fzf_completion

fpath+=( /tmp/Aloxaf/pure )
autoload -U promptinit; promptinit
prompt pure
```

**Comment by Aloxaf** [comment]
It seems to be the problem of _Alacritty_. In _konsole_ everything is OK.

It's totally broken in Alacritty. It may take some time for me to figure out if it is Alacritty's bug or my configure's bug.
![Peek 2019-12-31 15-14](https://user-images.githubusercontent.com/17017672/71613266-5bbcf400-2be0-11ea-997c-d459ead47852.gif)

**Comment by lincheney** [comment]
I think I've managed to find it.
Can you try with latest on master? (https://github.com/lincheney/fzf-tab-completion/commit/edd58e07147f9e53958123837c68adae0bcbd106)
It seems to happen due to the way alacritty handles 0x7f differently from other terminals and only when the text doesn't fit in the terminal width.

**Comment by Aloxaf** [comment]
Thank you. It works well now, but still have the same problem with `zsh-autosuggestions` enabled.

![Peek 2020-01-04 13-56](https://user-images.githubusercontent.com/17017672/71760530-21ae6380-2efa-11ea-823a-1dfc783d48ab.gif)

BTW I have switched to konsole~ the simplest way to solve this problem

**Comment by lincheney** [comment]
ok, with autosuggestions and the pure prompt, I've managed to reproduce the bug.
Can you try again with https://github.com/lincheney/fzf-tab-completion/commit/848f7692ec1d1dae94d4173aa4d27a782deba70b
it calls `zle reset-prompt` after completion now

**Comment by Aloxaf** [comment]
No problem now. Thanks a lot!
