### ISSUE TITLE
Completion on empty command stopped working

### ISSUE THREAD

**Issue by przepompownia** [lincheney/fzf-tab-completion#56]
I managed to reproduce this behavior on a fresh user with `~/.bashrc` containing only
```sh
. /usr/share/bash-completion/bash_completion
. "$(realpath "$(dirname ${BASH_SOURCE[0]})")/.src/external/fzf-tab-completion/bash/fzf-bash-completion.sh"
bind -x '"\t": fzf_bash_completion'
```
For example, after trying to complete `gi` I expect `git` etc. but all available commands are shown:
![image](https://user-images.githubusercontent.com/11404453/205468082-8f5eb941-c9e7-4dd8-ac57-db2b22f6b51b.png)

Using `git bisect` I found that it occurs from c692adbb3ae865b5f4fec6ff902314d456ae5cd6 After switching to it's parent completion working as expected:
![image](https://user-images.githubusercontent.com/11404453/205468056-72bf3f48-f09e-4e75-ad6f-7afa73bcdcf8.png)

- bash version: 5.2-2+b1 (Debian Sid)
- bash-completion: 2.11-6

**Comment by lincheney** [comment]
Thanks for the bug report.
I've just pushed up https://github.com/lincheney/fzf-tab-completion/commit/fe4117c7146278476dcb9ac4eb4760528f3f6586 which I think solves this issue.
Can you give it a try and let me know?

**Comment by przepompownia** [comment]
It seems to work. Thank you @lincheney 

Btw. I looked into the fe4117c and see (thanks to the change of an indentation) that `grep` is not prepended with `command` to avoid treat is as an alias or an user defined function. If I remember, it can avoid problems (for example, user defined `grep` command has enabled Perl regular expressions).
