### ISSUE TITLE
Spaces aren't escaped when autocompleting filenames with git

### ISSUE THREAD

**Issue by exchgr** [lincheney/fzf-tab-completion#57]
# Issue
If I have a file called `"a b.txt"`, it's escaped correctly when tab-completing with vim:
```bash
$ vim a<tab>
```
results in:
```bash
$ vim a\ b.txt
```

however, with git:
```bash
$ git checkout a<tab>
```
results in:
```bash
$ git checkout a b.txt
```

# System info
Hardware: MacBook Pro 13" M1 2020
OS: macOS 13.1
shell: GNU bash, version 5.2.12(1)-release (aarch64-apple-darwin22.1.0) (installed from homebrew)
`fzf-tab-completion` commit: 27936a7 
Relevant `.bashrc`, with no fzf-specific environment variables set:
```bash
source ~/.fzf-tab-completion/bash/fzf-bash-completion.sh
bind -x '"\t": fzf_bash_completion'
```
`gsed` and `gawk` are installed from homebrew
```bash
$ type gsed
gsed is /opt/homebrew/bin/gsed
$ type gawk
gawk is /opt/homebrew/bin/gawk
```

**Comment by lincheney** [comment]
What does `complete -p git` show?
Also when you are tab completing without fzf, does it escape properly?

**Comment by exchgr** [comment]
```bash
$ complete -p git
complete -o bashdefault -o default -o nospace -F _fzf_path_completion git
```

without fzf:
```bash
$ git checkout a<tab>
```
results in:
```bash
$ git checkout a\ b.txt
```

**Comment by lincheney** [comment]
I've managed to reproduce it, seems to be a bug with escaping not being applied to fallback completions.
I've pushed some fixes to master, are you able to give it a try?

**Comment by exchgr** [comment]
It works, thanks!
