### ISSUE TITLE
support for fish?

### ISSUE THREAD

**Issue by emilBeBri** [lincheney/fzf-tab-completion#58]
Hi this looks great, but I mostly use fish for interactive use. Would it be possible for you to support this?

**Comment by lincheney** [comment]
I don't personally use fish so its not something I'm going to be adding in
and tbh I'm unlikely to take PRs for it either as I won't be able to maintain it.
(if you find some other project that does this instead, I'm happy to add it to the `Related Projects` section in the README though)

**Comment by emilBeBri** [comment]
Ok, that's reasonable!
