### ISSUE TITLE
Not working example in bash

### ISSUE THREAD

**Issue by przepompownia** [lincheney/fzf-tab-completion#63]
Assuming that `~/.vim` exists, try to complete directory inside
```bash
(exec "$(command -pv nvim)" -u ~/.vi
```
I see no results.

Using alternative shortcut `"\es": menu-complete` in `~/.inputrc` I get `~/.vim` in results.

**Comment by lincheney** [comment]
Thanks for the bug report.
I've just pushed up fe55b78679227a477cc4987299d432e5726aee9d which I think solves this issue.
Can you give it a try and let me know?

**Comment by przepompownia** [comment]
The change looks non-trivially and works

![image](https://user-images.githubusercontent.com/11404453/217541880-d2c00f4f-6b8b-462c-9bd3-f62f567205dd.png)

Thanks!
