### ISSUE TITLE
Don't flush when completion items less than two

### ISSUE THREAD

**Issue by adoyle-h** [lincheney/fzf-tab-completion#64]
I'm using latest version of fzf-tab with bash 5.2.2.

## Description

When only one completion item, the flush of 'Loading matches ...'

![CleanShot 2023-02-15 at 03 47 19](https://user-images.githubusercontent.com/1998490/218844120-493ff892-248f-4855-a94d-b48efbd7433c.gif)

When no completion matched, the flush still exists,

![CleanShot 2023-02-15 at 03 50 32](https://user-images.githubusercontent.com/1998490/218845836-59cccf1d-149d-499d-836f-fd0492abde76.gif)

## What I expect

No flush and no window pop up when the size of completion items less than two.

**Comment by lincheney** [comment]
Not sure this is truly fixable
Bash/readline clears the prompt line before the keybind function is run. The flicker is unavoidable.
See https://github.com/lincheney/fzf-tab-completion#custom-loading-message
