### ISSUE TITLE
No completion for "which" command

### ISSUE THREAD

**Issue by adoyle-h** [lincheney/fzf-tab-completion#66]
## Problem

There is no completion for `which` command.

## Expected

It should list available commands.

## Environments

fzf-tab-completion: commit d88bf5b6
iTerm2: 3.5.0beta10
bash: 5.2.2
tmux: 3.3a

**Comment by lincheney** [comment]
Can you confirm, when you run `complete | grep which` do you get something like `complete -c which`

**Comment by adoyle-h** [comment]
<img width="288" alt="CleanShot 2023-03-09 at 18 31 59@2x" src="https://user-images.githubusercontent.com/1998490/223997748-1b72f7aa-b25f-4c49-af56-4f2c905c00ba.png">

And `which <Tab>` will list commands in my shell when fzf-tab-completion disabled.

**Comment by lincheney** [comment]
This is fixed in https://github.com/lincheney/fzf-tab-completion/commit/61e47000cb21ab85f83341903b7507ee1b7e0ae9

**Comment by adoyle-h** [comment]
Great! Thank you!
