### ISSUE TITLE
Tab complete hidden files?

### ISSUE THREAD

**Issue by jessemillar** [lincheney/fzf-tab-completion#7]
`fzf` on its own and `zsh` on its own can find/complete hidden files and directories (e.g. `.circleci`) but when I enable the `fzf-tab-completion.sh` script via the README instructions, only non-hidden files/directories are suggested on tab. Is there an option specific to this script that I'm missing?

**Comment by lincheney** [comment]
I can't reproduce this issue, I can get hidden files to show up in the completion when the word I'm completing begins with `.`, which is the same behaviour I get with normal zsh.
Can you provide a minimal `.zshrc` that I can use to reproduce your issue?

**Comment by jessemillar** [comment]
I can definitely try to get you a minimal config, but first, just to make sure we're on the same page, if you have the following files in a directory:
```
test.md
testing.md
.test
.testing
```
and type:
```
vim te
```
followed by a Tab, your `fzf` window suggests all four files? Mine does not, but if I type:
```
vim .te
```
(with the preceeding period), it suggests both hidden files.

Ideally, I'd like for `vim te<Tab>` to suggest all four files.

**Comment by lincheney** [comment]
With your example, if I do `vim te` then press tab, I get only the 2 results, but this happens both with fzf tab completion and "normal" zsh completion, so I'm getting consistent results with both. (More precisely with normal zsh completion, it first completes to `vim test` then I press tab again then it shows me the 2 results).

Are you saying that with `vim te` you get 4 results with normal zsh completion but only 2 with fzf tab completion?

**Comment by jessemillar** [comment]
Ah. I hadn't tested with vanilla zsh completion. I just did and I get the same result you describe. If that's the expected functionality, I can accept that. I'd just hoped there was a way to get all results suggested but I imagine you're sourcing your autocomplete options from zsh which means your script can't magically add that functionality.

**Comment by lincheney** [comment]
Yep, that's right, the fzf completion just uses whatever results zsh gives it.
There might be a way to configure zsh to get the behaviour you want and then hopefully fzf tab completion should just automatically pick that up.

**Comment by l4kr** [comment]
Stop this bs. Just put `setopt globdots` in your .zshrc (or wherever you deem it best) and be done with it. It will suggest hidden files just like any files. Idk why there's so many issues about this - none of them mentioning the actual fix.
