### ISSUE TITLE
fzf not shown after prefix autocompletion (bash)

### ISSUE THREAD

**Issue by treequin** [lincheney/fzf-tab-completion#78]
I'm using bash and I wanted to use the common prefix autocompletion but I've ran into the problem that fzf is not shown after a prefix was completed.

So I replicated the example from the README with these results:

For example, if we have following files in a directory:
```
abcdef-1234
abcdef-5678
abc
other
```
With `FZF_COMPLETION_AUTO_COMMON_PREFIX=true`:
- [x] when completing `ls <tab>`, it will display fzf with all 4 files (as normal)
- [x] when completing `ls a<tab>`, it will automatically complete to `ls abc`.
- [ ] Pressing tab again will show fzf with the first 3 files. **_For me it just shows "Loading matches ..." for a moment._**
- [x] when completing `ls abcd<tab>` it will show fzf with the first 2 files (as normal)

With `FZF_COMPLETION_AUTO_COMMON_PREFIX_PART=true` set as well:
- [x] when completing `ls abcd<tab>`, it will automatically complete to `ls abcdef-`.
- [ ] Pressing tab again will show fzf with the first 2 files. **_Same as before, "Loading matches ..." but no fzf._**

In addition to the above, when `FZF_COMPLETION_AUTO_COMMON_PREFIX_PART=true` is set fzf is _never_ shown, I tried it with every command I could think of and the tab completion only works if it can match a prefix or a full name, if it can't it shows "Loading matches ..." and nothing else.

I thought it could be caused by some option I'd changed in fzf, but I tried it on a fresh install with the same results. I also tried adding the variables to .bashrc instead of setting them from the terminal but it made no difference.

I'm fairly new to using the command line, so please let me know if I'm missing something obvious or if there's any troubleshooting I should do.

Thank you.

**Comment by lincheney** [comment]
Hi, I've pushed this commit https://github.com/lincheney/fzf-tab-completion/commit/aa71a4c202149dbe958d47b129ddc26d2592b793 which I think solves the issue
Are you able to test it out?

**Comment by treequin** [comment]
Tested it and everything is working for me now. Thank you!
