### ISSUE TITLE
`possible retry loop` with absolute path to command

### ISSUE THREAD

**Issue by przepompownia** [lincheney/fzf-tab-completion#80]
Hi,

please try to complete at the end of `/usr/bin/tar`, `/usr/bin/nmcli` etc. 

I get 
```
/usr/bin/nmcli: possible retry loop
/usr/bin/tar: possible retry loop
```

**Comment by lincheney** [comment]
Hello

Unfortunately I'm not able to reproduce this behaviour.
When I try to tab complete `/usr/bin/tar` it simply adds a space at the end as expected.
Are you able to provide some `set -x` debugging as before? To help identify where the issue is coming from.

**Comment by przepompownia** [comment]
Uploaded to https://asciinema.org/a/tStOK31fIkJCAyuvIpgjDq5jU

**Comment by lincheney** [comment]
oh i see, i was trying `/usr/bin/tar` but it is actually `/usr/bin/tar ` that is problematic
in that case I am getting the same issue
let me see what is happening ...

**Comment by lincheney** [comment]
I've pushed this commit https://github.com/lincheney/fzf-tab-completion/commit/1ec392c710215cfa45078d2b5b469c6119e89fb0 which I think solves the issue
Are you able to test it out?

**Comment by przepompownia** [comment]
It resolves the problem for me, thanks!
