### ISSUE TITLE
No add space after path for commands without completion

### ISSUE THREAD

**Issue by d-enk** [lincheney/fzf-tab-completion#81]
![2023-10-30 20-51](https://github.com/lincheney/fzf-tab-completion/assets/43112758/da3ac9d6-4801-43e2-8804-1c40d4c77209)

**Comment by lincheney** [comment]
Hi, can you show me the output of running `complete -p -D`

**Comment by d-enk** [comment]
> Hi, can you show me the output of running `complete -p -D`

`complete -F _comp_complete_load -D`

**Comment by lincheney** [comment]
Hi, are you able to try out a possible fix I have pushed here https://github.com/lincheney/fzf-tab-completion/commit/6539481338d7fdc53301aaa0bdbd6728be66c7aa

**Comment by d-enk** [comment]
Cool, everything works, thanks
I couldn't quickly find a good solution myself)

**Comment by d-enk** [comment]
@lincheney, Oooops

![Peek 2023-11-08 18-37](https://github.com/lincheney/fzf-tab-completion/assets/43112758/6645ffc7-18a7-40c4-8c0d-7da56b1b4fa9)

**Comment by lincheney** [comment]
ahhh good catch

**Comment by lincheney** [comment]
OK I think this one should do it https://github.com/lincheney/fzf-tab-completion/commit/f6f83c88eca0fc07f7820dd8bb6c7ea75ef478c5
