### ISSUE TITLE
Readline installation vs bash?

### ISSUE THREAD

**Issue by hoclun-rigsep** [lincheney/fzf-tab-completion#83]
What are advantages of using readline installation vs bash?

**Comment by lincheney** [comment]
For bash, not much, all the results and other behaviour should be essentially the same, and in fact the readline one is less likely to be compatible (how bash is linked, the OS etc.)
Only thing I think is that readline will show fzf *below* the prompt as opposed to clearing the prompt then showing fzf, which can look at bit nicer.
