### ISSUE TITLE
Feature: Add support for "no_empty_cmd_completion"

### ISSUE THREAD

**Issue by systemmonkey42** [lincheney/fzf-tab-completion#88]
The function `fzf_bash_completion()` should honor the bash/readline setting `no_empty_cmd_completion`

for example
```bash
fzf_bash_completion() {
    if [[ -z "${READLINE_LINE}" ]] && shopt -q no_empty_cmd_completion; then
        return 1
    fi
    ...
```

This helps prevent <kbd>tab</kbd> on an empty line triggering completion of every command in the path. (which for me can take
up to 15 seconds)

(Pressing at least one letter then <kbd>tab</kbd> will still complete commands.)

**Comment by lincheney** [comment]
implemented in 4dbb200c3cd448eb71b7ef9b275a9d84726a5063
