### ISSUE TITLE
Possible to backspace prompt

### ISSUE THREAD

**Issue by clinta** [lincheney/fzf-tab-completion#93]
If I run `ls abc<tab>` the `abc` portion of the search is permanent, I cannot edit it to broaden my search without canceling the search first. Is there any way to adjust this behavior?

**Comment by d-enk** [comment]
no, you can't do that
at least because for a different input there will be a different stream of lines for fzf

**Comment by lincheney** [comment]
Hi

> no, you can't do that at least because for a different input there will be a different stream of lines for fzf

It's exactly this. Since the completion functions (not fzf-tab-completion) give you different matches depending on what you have already entered.

As an example, if you do `ls <tab>` it will show you only files whereas `ls -<tab>` will show you only options, they are not subsets of each other. You must re-trigger the completion to go from one to the other.

**Comment by clinta** [comment]
Is it possible with a keybind perhaps, when backspace is entered and the search query is empty, re-run tab completion with a new prompt less the last character?

**Comment by lincheney** [comment]
If you are using bash, then unfortunately keybinds cannot currently re-run tab completion.

If you are using zsh you may be able to get something working using https://github.com/lincheney/fzf-tab-completion?tab=readme-ov-file#specifying-keybindings.
Essentially, if you can make a binding `key:function` where pressing `key` will stop fzf and invoke the given shell function.
You can try write a function like:
```
fzf-completion-backspace-and-retry() {
    # modify BUFFER or LBUFFER or something
    LBUFFER=...
    repeat-fzf-completion
}
```
However, afaict there is no way to happen only if the search query is empty (ie this keybind will end up always run this function).
