### ISSUE TITLE
 cd to sub directory of directory with spaces does not work as slash gets removed

### ISSUE THREAD

**Issue by overtomanu** [lincheney/fzf-tab-completion#96]
OS    - Linux Fedora
Shell - Bash

when doing  cd to sub directory of directory with spaces, it removes slash and cd to directory doesn't work. Refer below gif
 
![output](https://github.com/lincheney/fzf-tab-completion/assets/4481775/3f742819-3b4f-450c-89c3-20452809c762)

I have following things in the bashrc file

```sh
source "$HOME/fzf-tab-completion-master/bash/fzf-bash-completion.sh"
bind -x '"\t": fzf_bash_completion'
export FZF_COMPLETION_AUTO_COMMON_PREFIX=true
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
```

Might be related to https://github.com/lincheney/fzf-tab-completion/issues/91, I have logged this issue as I was not fully sure if this is a duplicate.

**Comment by lincheney** [comment]
Hello
I have made this commit which I *think* should fix the issue https://github.com/lincheney/fzf-tab-completion/commit/b8e71337d3a78a67f858f0fcbc4193aff5cb0720

**Comment by overtomanu** [comment]
@lincheney Thanks. I just tested it and it works. Closing this issue.
